name: wealthy
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  mysql1: ^0.19.2
  http: ^0.13.6
  geolocator: ^7.7.0
  google_fonts: ^4.0.3
  flutter_svg: ^0.22.0
  form_field_validator: ^1.0.1
  table_calendar: ^3.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
